[workspace]
members = [
    "tempest",
    "tempest-source",
    "tempest-source-mock",
    "tempest-source-redis",
    "tempest-book",
    "tempest-source-redis/examples/topology-redis-stream"
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
