version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.37-stretch
      - image: circleci/redis:5.0.5-stretch

    steps:
      - checkout

      - run:
          name: Update Apt Cache
          command: sudo apt-get update
      - run:
          name: Install base packages
          command: sudo apt-get install -y wget build-essential python2.7 make gcc redis-tools

      - run:
          name: Redis info
          command: redis-cli info

      - run:
          name: Cargo test
          command: RUST_BACKTRACE=full cargo test -- --nocapture