[package]
name = "tempest"
version = "0.1.0"
authors = ["grippy <gmelton@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8.1"
config = "0.9"

rand = "0.3"
bytes = "0.4"
byteorder = "1.1"
futures = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-tcp = "0.1"
tokio-signal = "0.2"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
structopt = "0.2"
uuid = { version = "0.7", features = ["v4"] }

# redis_streams = { git = "https://github.com/grippy/redis-streams-rs.git" }
# redis_streams = {path = "../../redis-streams-rs"}