[package]
name = "topology_example"
version = "0.1.0"
authors = ["grippy <gmelton@gmail.com>"]
edition = "2018"

[dependencies]
pretty_env_logger = "0.3.0"
tempest = {path = "../../../tempest"}
tempest-source-redis = {path = "../../../tempest-source-redis"}
